"""
This file is auto-generated by robot_commander_builder.py
You should move this file to the gerri/operator/your_robot_directory
"""

from pubsub import pub
import datetime
import time
from utils.time_sync_manager import time_sync
print(time_sync.timestamp())

def timestamp():
    return time_sync.timestamp()

class TestRobotCommander:
    def __init__(self, robot_info, operator_info, **params):
        self.robot_info = robot_info
        self.robot_id = robot_info['id']
        self.robot_category = robot_info['category']
        self.robot_model = robot_info['model']
        self.operator_info = operator_info
        pub.subscribe(self.receive_message, 'receive_message')

    def send_command(self, topic, value):
        command = {"topic": topic, "value": value}
        pub.sendMessage('send_command', command=command)


    def connect(self):
        topic = "connect"
        value = {}
        self.send_command(topic=topic, value=value)

    def disconnect(self):
        topic = "disconnect"
        value = {}
        self.send_command(topic=topic, value=value)

    def get_lease(self, value=None, option=None):
        topic = "get_lease"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def release_lease(self, value=None, option=None):
        topic = "release_lease"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def get_ptz_status(self):
        topic = "get_ptz_status"
        value = {}
        self.send_command(topic=topic, value=value)

    def answer_question(self, value=None, option=None):
        topic = "answer_question"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def walk(self, value=None, option=None):
        topic = "walk"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def stand(self, value=None, option=None):
        topic = "stand"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def sit(self, value=None, option=None):
        topic = "sit"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def action_stop(self, value=None, option=None):
        topic = "action_stop"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def move(self, value=None, option=None):
        topic = "move"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def run_mission(self, value=None, option=None):
        topic = "run_mission"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def stop_mission(self, value=None, option=None):
        topic = "stop_mission"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def pause_mission(self, value=None, option=None):
        topic = "pause_mission"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def resume_mission(self, value=None, option=None):
        topic = "resume_mission"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def dock(self, value=None, option=None):
        topic = "dock"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def spot_ptz_absolute(self, value=None, option=None):
        topic = "spot_ptz_absolute"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def spot_ptz_relative(self, value=None, option=None):
        topic = "spot_ptz_relative"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def spot_ptz_initialize(self, value=None, option=None):
        topic = "spot_ptz_initialize"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def spot_ptz_set_focus(self, value=None, option=None):
        topic = "spot_ptz_set_focus"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def spot_ptz_set_focus_relative(self, value=None, option=None):
        topic = "spot_ptz_set_focus_relative"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def set_compositor(self, value=None, option=None):
        topic = "set_compositor"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def light_controll(self, value=None, option=None):
        topic = "light_controll"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def predict_kospo(self, value=None, option=None):
        topic = "predict_kospo"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def call_predict_api(self, value=None, option=None):
        topic = "call_predict_api"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)

    def auto_return(self, value=None, option=None):
        topic = "auto_return"
        value = {}
        value["value"] = value
        value["option"] = option
        self.send_command(topic=topic, value=value)
