# Auto-generated keyboard/mouse controller map
KEYBOARD_MOUSE_CONTROLLER_MAP = {
    '0': None,
    '1': None,
    '2': None,
    '3': None,
    '4': None,
    '5': None,
    '6': None,
    '7': None,
    '8': None,
    '9': None,
    'A': None,
    'ALT': None,
    'B': None,
    'BACKSPACE': None,
    'C': None,
    'CAPSLOCK': None,
    'CTRL': None,
    'D': None,
    'DELETE': None,
    'DOWN': None,
    'E': None,
    'END': None,
    'ENTER': None,
    'ESC': None,
    'F': None,
    'F1': None,
    'F10': None,
    'F11': None,
    'F12': None,
    'F2': None,
    'F3': None,
    'F4': None,
    'F5': None,
    'F6': None,
    'F7': None,
    'F8': None,
    'F9': None,
    'G': None,
    'H': None,
    'HOME': None,
    'I': None,
    'INSERT': None,
    'J': None,
    'K': None,
    'L': None,
    'LEFT': None,
    'M': None,
    'MENU': None,
    'MOUSE_BACK': None,
    'MOUSE_FORWARD': None,
    'MOUSE_LEFT': None,
    'MOUSE_MIDDLE': None,
    'MOUSE_MOVE_X': None,
    'MOUSE_MOVE_Y': None,
    'MOUSE_RIGHT': None,
    'MOUSE_WHEEL_DOWN': None,
    'MOUSE_WHEEL_UP': None,
    'N': None,
    'NUMLOCK': None,
    'NUMPAD_0': None,
    'NUMPAD_1': None,
    'NUMPAD_2': None,
    'NUMPAD_3': None,
    'NUMPAD_4': None,
    'NUMPAD_5': None,
    'NUMPAD_6': None,
    'NUMPAD_7': None,
    'NUMPAD_8': None,
    'NUMPAD_9': None,
    'NUMPAD_ADD': None,
    'NUMPAD_DECIMAL': None,
    'NUMPAD_DIVIDE': None,
    'NUMPAD_ENTER': None,
    'NUMPAD_MULTIPLY': None,
    'NUMPAD_SUBTRACT': None,
    'O': None,
    'P': None,
    'PAGEDOWN': None,
    'PAGEUP': None,
    'PAUSE': None,
    'PRINTSCREEN': None,
    'Q': None,
    'R': None,
    'RIGHT': None,
    'S': None,
    'SCROLLLOCK': None,
    'SHIFT': None,
    'SPACE': None,
    'T': None,
    'TAB': None,
    'U': None,
    'UP': None,
    'V': None,
    'W': None,
    'WINDOWS': None,
    'X': None,
    'Y': None,
    'Z': None}

def key_mouse_control(command):
    key = command['key_control']
    mouse_d_move = command['mouse_d_move']
    mouse_d_wheel = command['mouse_d_wheel']
    mouse_click = command['mouse_click']

    if "W" in key:
        pass
    elif "S" in key:
        pass
    if "A" in key:
        pass
    elif "D" in key:
        pass
    if "Q" in key:
        pass
    elif "E" in key:
        pass