"""
This file is auto-generated by robot_commander_builder.py
You should move this file to the gerri/operator/your_robot_directory
"""

from pubsub import pub
import datetime
import time
from utils.time_sync_manager import time_sync
print(time_sync.timestamp())

def timestamp():
    return time_sync.timestamp()

class SpotCommander:
    def __init__(self, robot_info, operator_info, **params):
        self.robot_info = robot_info
        self.robot_id = robot_info['id']
        self.robot_category = robot_info['category']
        self.robot_model = robot_info['model']
        self.operator_info = operator_info
        pub.subscribe(self.receive_message, 'receive_message')

    def send_command(self, topic, value):
        command = {"topic": topic, "value": value}
        pub.sendMessage('send_command', command=command)


    def move(self, vx=0.0, vy=0.0, vth=0.0):
        topic = "move"
        value = {}
        value["vx"] = vx
        value["vy"] = vy
        value["vth"] = vth
        self.send_command(topic=topic, value=value)

    def move_waypoint(self, poi):
        topic = "move_waypoint"
        value = {}
        value["poi"] = poi
        self.send_command(topic=topic, value=value)

    def test_method(self):
        topic = "test_method"
        value = {}
        self.send_command(topic=topic, value=value)
